// Package vendorDirectFulfillmentTransactionsV1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package vendorDirectFulfillmentTransactionsV1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	runt "runtime"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TransactionStatus.
const (
	Failure    TransactionStatus = "Failure"
	Processing TransactionStatus = "Processing"
	Success    TransactionStatus = "Success"
)

// Error Error response returned when the request is unsuccessful.
type Error struct {
	// Code An error code that identifies the type of error that occurred.
	Code string `json:"code"`

	// Details Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// Message A message that describes the error condition.
	Message string `json:"message"`
}

// ErrorList A list of error responses returned when a request is unsuccessful.
type ErrorList = []Error

// GetTransactionResponse The response schema for the getTransactionStatus operation.
type GetTransactionResponse struct {
	// Errors A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// TransactionStatusRenamedByExtension The payload for the getTransactionStatus operation.
	TransactionStatusRenamedByExtension *TransactionStatusRenamedByExtension `json:"payload,omitempty"`
}

// Transaction The transaction status details.
type Transaction struct {
	// Errors A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// Status Current processing status of the transaction.
	Status TransactionStatus `json:"status"`

	// TransactionId The unique identifier sent in the 'transactionId' field in response to the post request of a specific transaction.
	TransactionId string `json:"transactionId"`
}

// TransactionStatus Current processing status of the transaction.
type TransactionStatus string

// TransactionStatusRenamedByExtension The payload for the getTransactionStatus operation.
type TransactionStatusRenamedByExtension struct {
	// TransactionStatus The transaction status details.
	TransactionStatus *Transaction `json:"transactionStatus,omitempty"`
}

var (
	JSONMarshal    = json.Marshal
	JSONUnmarshal  = json.Unmarshal
	JSONNewDecoder = func(r io.Reader) interface{ Decode(v any) error } { return json.NewDecoder(r) }
	JSONNewEncoder = func(w io.Writer) interface{ Encode(v any) error } { return json.NewEncoder(w) }
)

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// RetryOptions defines the configuration for RetryTransport.
// It allows users to DIY their retry strategy, such as exponential backoff
// or header-based rate-limit backoff.
type RetryOptions struct {
	MaxRetries int
	// RetryOn returns true if the request should be retried.
	RetryOn func(resp *http.Response, err error) bool
	// Backoff returns the duration to wait before the next retry.
	// It can use the attempt count or inspect response headers (e.g., x-amzn-RateLimit-Limit).
	Backoff func(attempt int, resp *http.Response) time.Duration
}

// RetryTransport is an http.RoundTripper that retries requests based on RetryOptions.
type RetryTransport struct {
	Next    http.RoundTripper
	Options RetryOptions
}

// DefaultRetryOptions provides a basic DIY example for SP-API retries.
var DefaultRetryOptions = RetryOptions{
	MaxRetries: 3,
	RetryOn: func(resp *http.Response, err error) bool {
		if err != nil {
			return true
		}
		// Typically retry on 429 (Too Many Requests) or 5xx server errors
		if resp.StatusCode == 429 || resp.StatusCode >= 500 {
			return true
		}
		return false
	},
	Backoff: func(attempt int, resp *http.Response) time.Duration {
		// Example: Check for SP-API rate limit header
		// if resp != nil && resp.Header.Get("x-amz-retry-after") != "" { ... }

		// Fallback to exponential backoff
		// 100ms, 200ms, 400ms...
		return time.Duration(100*(1<<uint(attempt))) * time.Millisecond
	},
}

// RoundTrip implements http.RoundTripper
func (t *RetryTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	var resp *http.Response
	var err error

	for attempt := 0; attempt <= t.Options.MaxRetries; attempt++ {
		// Clone request body so we can retry if needed
		var reqBodyBytes []byte
		if req.Body != nil && req.GetBody == nil {
			reqBodyBytes, _ = io.ReadAll(req.Body)
			req.Body = io.NopCloser(bytes.NewReader(reqBodyBytes))
			req.GetBody = func() (io.ReadCloser, error) {
				return io.NopCloser(bytes.NewReader(reqBodyBytes)), nil
			}
		}

		// Make sure to use the fresh body for each retry
		if req.GetBody != nil {
			req.Body, _ = req.GetBody()
		}

		resp, err = t.Next.RoundTrip(req)

		// Check if we need to retry
		if attempt < t.Options.MaxRetries && t.Options.RetryOn != nil && t.Options.RetryOn(resp, err) {
			// Drain and close body before retrying
			if resp != nil && resp.Body != nil {
				io.Copy(io.Discard, resp.Body)
				resp.Body.Close()
			}
			wait := t.Options.Backoff(attempt, resp)

			// Respect request context cancellation
			select {
			case <-req.Context().Done():
				return resp, req.Context().Err()
			case <-time.After(wait):
			}
			continue
		}
		break
	}
	return resp, err
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// The user agent header identifies your application, its version number, and the platform and programming language you are using.
	// You must include a user agent header in each request submitted to the sales partner API.
	UserAgent string
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	// setting the default useragent
	if client.UserAgent == "" {
		client.UserAgent = fmt.Sprintf("selling-partner-api-sdk/v2.0 (Language=%s; Platform=%s-%s)", strings.Replace(runt.Version(), "go", "go/", -1), runt.GOOS, runt.GOARCH)
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetTransactionStatus request
	GetTransactionStatus(ctx context.Context, transactionId string) (*http.Response, error)
}

func (c *Client) GetTransactionStatus(ctx context.Context, transactionId string) (*http.Response, error) {
	req, err := NewGetTransactionStatusRequest(c.Server, transactionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	req.Header.Set("User-Agent", c.UserAgent)
	rsp, err := c.Client.Do(req)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// NewGetTransactionStatusRequest generates requests for GetTransactionStatus
func NewGetTransactionStatusRequest(server string, transactionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "transactionId", runtime.ParamLocationPath, transactionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vendor/directFulfillment/transactions/v1/transactions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetTransactionStatusWithResponse request
	GetTransactionStatusWithResponse(ctx context.Context, transactionId string) (*GetTransactionStatusResp, error)
}

type GetTransactionStatusResp struct {
	Body         []byte // Might be nil if decoded via streaming
	HTTPResponse *http.Response
	JSON200      *GetTransactionResponse
	JSON400      *GetTransactionResponse
	JSON401      *GetTransactionResponse
	JSON403      *GetTransactionResponse
	JSON404      *GetTransactionResponse
	JSON415      *GetTransactionResponse
	JSON429      *GetTransactionResponse
	JSON500      *GetTransactionResponse
	JSON503      *GetTransactionResponse
}

// Status returns HTTPResponse.Status
func (r GetTransactionStatusResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransactionStatusResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetTransactionStatusWithResponse request returning *GetTransactionStatusResp
func (c *ClientWithResponses) GetTransactionStatusWithResponse(ctx context.Context, transactionId string) (*GetTransactionStatusResp, error) {
	rsp, err := c.GetTransactionStatus(ctx, transactionId)
	if err != nil {
		return nil, err
	}
	return ParseGetTransactionStatusResp(rsp)
}

// ParseGetTransactionStatusResp parses an HTTP response from a GetTransactionStatusWithResponse call
func ParseGetTransactionStatusResp(rsp *http.Response) (*GetTransactionStatusResp, error) {
	defer func() { _ = rsp.Body.Close() }()

	response := &GetTransactionStatusResp{
		HTTPResponse: rsp,
	}

	contentType := rsp.Header.Get("Content-Type")

	switch {
	case strings.Contains(contentType, "json") && rsp.StatusCode == 200:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON200 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 400:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON400 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 401:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON401 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 403:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON403 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 404:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON404 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 415:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON415 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 429:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON429 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 500:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON500 = &dest
		return response, nil
	case strings.Contains(contentType, "json") && rsp.StatusCode == 503:
		var dest GetTransactionResponse
		if err := JSONNewDecoder(rsp.Body).Decode(&dest); err != nil && err != io.EOF {
			return nil, err
		}
		response.JSON503 = &dest
		return response, nil
	}

	bodyBytes, err := io.ReadAll(rsp.Body)
	if err != nil {
		return nil, err
	}
	response.Body = bodyBytes

	return response, nil
}
